default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: store_book_development
  username: store_user
  password: store_user

test:
  <<: *default
  database: store_user_test
  username: store_user
  password: store_user

production:
  <<: *default
  database: store_user_production
  username: store_user
  password: store_user
